config/routes.rb
Rails.application.routes.draw do
  root 'escenarios#index'
  devise_for :users, controllers: {sessions: 'users/sessions'}
  get 'ajax/buscar_candidato/:tipo_escenario/:objeto_id', to: "ajax#buscar_candidato"
  get 'ajax/obtener_restricciones_html/:escenario_id', to: 'ajax#get_restricciones_html'
  post 'ajax/asignar_candidato/:escenario_id/:objeto_id/:candidato_id/', to: "ajax#asignar_candidato_objeto_escenario"
  post 'candidatos/upload_csv', to: 'upload#create', as: 'upload_candidatos_csv'
  resources :candidatos
  resources :escenarios
end

app/views/partials/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l8 s12">
        <h5 class="white-text">Este es el footer</h5>
        <p>es simple pero hecho con amor <3</p>
      </div>
      <div class="col l4 s12">Aquí pueden ir los enlaces de interés</div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container white-text">
      © 2017 INNORTE
    </div>
  </div>
</footer>

app/views/partials/_messages.html.erb
<%
mensajes = ''
unless flash[:alert].nil?
  if flash[:alert].is_a? String
    mensajes = flash[:alert]
  elsif flash[:alert].is_a? Array
    flash[:alert].map do |m|
      mensajes += "#{m}\\n"
    end
  end
end
mensajes_p = ''
unless flash[:notice].nil?
  if flash[:notice].is_a? String
    mensajes_p = flash[:notice]
  elsif flash[:notice].is_a? Array
    flash[:notice].map do |m|
      mensajes_p += "#{m}\\n"
    end
  end
end
%>
<% content_for :messages_js do %>
<%= "Electo.Messages.showMessage({title:'Algo salió mal...',text:'#{mensajes}',type:'error'});".html_safe unless mensajes.empty? %>
<%= "Electo.Messages.showMessage({title:'Hurra!',text:'#{mensajes_p}',type:'success'});".html_safe unless mensajes_p.empty? %>
<% end %>

app/views/partials/_navigator.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="<%= root_path %>" class="brand-logo center">Simulador de Escenario Electoral</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><b><%= link_to "Candidatos", candidatos_path %></b></li>
      <li><b><%= link_to "Escenarios", escenarios_path %></b></li>
      <li><b><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %></b></li>
    </ul>
  </div>
</nav>