config/routes.rb
Rails.application.routes.draw do
  root 'escenarios#index'
  devise_for :users, controllers: {sessions: 'users/sessions'}
  get 'ajax/buscar_candidato/:tipo_escenario/:objeto_id', to: "ajax#buscar_candidato"
  get 'ajax/obtener_restricciones_html/:escenario_id', to: 'ajax#get_restricciones_html'
  post 'ajax/asignar_candidato/:escenario_id/:objeto_id/:candidato_id/', to: "ajax#asignar_candidato_objeto_escenario"
  post 'candidatos/upload_csv', to: 'upload#create', as: 'upload_candidatos_csv'
  resources :candidatos
  resources :escenarios
end

app/models/candidato.rb
class Candidato < ApplicationRecord
  belongs_to :carto_mpio
  
end

app/controllers/candidatos_controller.rb
class CandidatosController < ApplicationController
  before_action :authenticate_user!
  before_action :get_all_candidatos, only: [:index]
  before_action :find_candidato, only: [:edit,:destroy,:update]
  before_action :get_all_mpios, only: [:new,:edit]
  def index
  end

  def new
    @candidato = Candidato.new
  end

  def create
    @candidato = Candidato.new(candidato_params)
    if @candidato.save
      respond_to do |f|
        f.html { redirect_to candidatos_path, notice: "Candidato creado" }
        f.json { render json: {created: true}}
      end
    else
      respond_to do |f|
        f.html { redirect_to :new, alert: @candidato.errors.full_messages }
        f.json { render json: {created: false, reason: @candidato.errors.full_messages}}
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @candidato.update(candidato_params)
      respond_to do |f|
        f.html { redirect_to candidatos_path, notice: "Se actualizó el candidato #{@candidato.nombre.mb_chars.titleize}"}
      end
    else
      respond_to do |f|
        f.html {redirect_to edit_candidato(@candidato.id), alert: @candidato.errors.full_messages }
      end
    end
  end

  def destroy
    @candidato.update(activo: false)
    respond_to do |f|
      f.html { redirect_to candidatos_path}
    end
  end

  def create_candidatos_csv
    if Candidato.add_csv params[:csv_candidatos]
      respond_to do |f|
        f.html {redirect_to candidatos_path, notice: "Los candidatos fueron importados correctamente"}
      end
    else
      respond_to do |f|
        f.html {redirect_to candidatos_path, alert: @candidatos.errors.full_messages}
      end
    end
  end

  private
  def candidato_params
    params.require(:candidato).permit(:nombre,:fecha_nacimiento,:sexo,:carto_mpio_id,:encuesta)
  end

  def get_all_candidatos
    @candidatos = Candidato.select("id, nombre, fecha_nacimiento, date_part('year',age(date('2018-07-01'),fecha_nacimiento)) as edad,sexo,encuesta,carto_mpio_id").where("activo = true")
  end

  def find_candidato
    @candidato = Candidato.find(params[:id])
  end

  def get_all_mpios
    @mpios = CartoMpio.all
  end
end

app/helpers/candidatos_helper.rb
module CandidatosHelper
end

app/views/candidatos/_form.html.erb
<%= form_with model: @candidato, local: true do |f| %>
<div class="input-field">
  <p><b>Nombre del Candidato</b></p>
  <%= f.text_field :nombre, placeholder: "Nombre del nuevo candidato", required: true, value: @candidato.nombre %>
</div>
<div class="input-field">
  <p><b>Fecha de nacimiento</b><p>
  <%= f.date_field :fecha_nacimiento, placeholder:"YYYY-MM-DD", max:"2017-12-10", required: true, value: (@candidato.id.nil? ? '' : @candidato.fecha_nacimiento.strftime('%Y-%m-%d') )%>
</div>
<div class="input-field">
  <p><b>Lugar de nacimiento</b></p>
  <%= f.select :carto_mpio_id, options_for_select(@mpios.map {|m| [m.nom_mun.mb_chars.titleize,m.id]},selected: @candidato.carto_mpio_id) %>
</div>
<div class="input-field">
  <p><b>Sexo</b></p>
    <%= f.radio_button :sexo, "true", id: 'candidato_sexo_true', required: true, checked: (true if @candidato.sexo) %>
    <%= f.label :sexo_true, "Masculino" %>
    <%= f.radio_button :sexo, "false", id: 'candidato_sexo_false', checked: (false if @candidato.sexo)  %>
    <%= f.label :sexo_false, "Femenino" %>
</div>
<div class="input-field">
  <p><b>Porcentaje de encuesta</b></p>
  <%= f.number_field :encuesta, min: 0, max: 100, step: "0.01", placeholder: "%",value: @candidato.encuesta %>
</div>
<div class="input-field">
  <%= f.submit (@candidato.id.nil? ? "Crear" : "Actualizar"),class:"btn btn-large waves waves-light red" %>
</div>
<% end %>
<% content_for :js do %>
$('select').material_select();
<% end %>

app/views/candidatos/_modal_upload_csv.html.erb
<a class="waves-effect waves-light btn modal-trigger red right tooltiped" href="#modalUploadFile" data-position="top" data-delay="50" data-tooltip="Crea candidatos a partir de un archivo csv"><i class="material-icons large">backup</i></a>
<div id="modalUploadFile" class="modal">
  <div class="modal-content">
    <h4>Sube tu archivo en formato CSV</h4>
    <%= form_with url: upload_candidatos_csv_path, method: :post, local: true, html: {multipart: true} do |f| %>
    <p>Selecciona tu archivo formateado:</p>
    <div class="file-field input-field">
      <div class="btn">
        <span>Archivo</span>
        <%= file_field_tag :csv_candidatos %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
    <div class="input-field">
      <%= submit_tag "Subir archivo", class: 'btn btn-large waves waves-light red' %>
    </div>
    <% end %>
  </div>
</div>
<% content_for :js do %>
$('.tooltipped').tooltip({delay: 50});
$('#modalUploadFile').modal();
<% end %>

app/views/candidatos/edit.html.erb
<h4>Editando al candidato <%= @candidato.nombre.mb_chars.titleize %></h4>
<%= render 'form' %>

app/views/candidatos/index.html.erb
<div class="row">
  <% if @candidatos.empty? %>
    <h3>Parece que no hay candidatos dados de alta en el sistema...</h3>
    <h4>podrías crear candidatos desde el botón inferior derecho</h4>
  <% else %>
    <% @candidatos.map do |c| %>
    <div class="col s12 m6 l4">
      <div class="card hoverable">
        <div class="card-content">
          <span class="card-title"><b>Candidato:</b> <%= c.nombre.titleize %></span>
          <p><b>Fecha de nacimiento:</b> <%= c.fecha_nacimiento.strftime("%d/%m/%Y") %></p>
          <p><b>Edad:</b> <%= c.edad.to_i %> años al día de la elección (01/07/2018).</p>
          <p><b>Sexo:</b> <%= c.sexo ? 'Hombre' : 'Mujer' %></p>
          <p><b>Encuesta:</b> <%= c.encuesta %>%</p>
          <p><b>Municipio de nacimiento:</b> <%= c.carto_mpio.nom_mun.titleize %></p>
        </div>
        <div class="card-action">
          <%= link_to "Editar", edit_candidato_path(c.id), class: 'btn waves' %>
          <%= link_to "Eliminar", candidato_path(c.id), class: "btn red waves right", method: :delete %>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
  <%= link_to new_candidato_path, class: "btn-floating btn-large waves-effect waves-light red #{'pulse' if @candidatos.empty?} actions-button" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>

app/views/candidatos/new.html.erb
<h4>Creando un nuevo candidato</h4>
<%= render 'modal_upload_csv' %>
<%= render 'form' %>

app/views/candidatos/show.html.erb
<h1>Candidatos#show</h1>
<p>Find me in app/views/candidatos/show.html.erb</p>