config/routes.rb
Rails.application.routes.draw do
  root 'escenarios#index'
  devise_for :users, controllers: {sessions: 'users/sessions'}
  get 'ajax/buscar_candidato/:tipo_escenario/:objeto_id', to: "ajax#buscar_candidato"
  get 'ajax/obtener_restricciones_html/:escenario_id', to: 'ajax#get_restricciones_html'
  post 'ajax/asignar_candidato/:escenario_id/:objeto_id/:candidato_id/', to: "ajax#asignar_candidato_objeto_escenario"
  post 'candidatos/upload_csv', to: 'upload#create', as: 'upload_candidatos_csv'
  resources :candidatos
  resources :escenarios
end

app/models/escenario.rb
class Escenario < ApplicationRecord
  belongs_to :user
  has_many :historico_escenario_dists
  has_many :historico_escenario_mpios

  validates :nombre, presence: true, uniqueness: true
  validates :tipo_escenario, presence: true, if: :it_is_under_parameters?

  def it_is_under_parameters?
    tipo_escenario.in?([1,2])
  end
end

app/controllers/escenarios_controller.rb
class EscenariosController < ApplicationController
  before_action :authenticate_user!
  rescue_from ActiveRecord::RecordNotFound, :with => :escenario_not_found
  before_action :get_escenarios_activos, only:[:index]
  before_action :new_escenario, only:[:new]
  before_action :find_escenario, except: [:index,:new,:create,:create_escenario_optimo_dist_prueba]
  before_action :is_active_escenario, only:[:edit,:show,:update]
  before_action :get_data_carto, only: [:show,:edit]

  def index
  end

  def new
  end

  def create
    @escenario = Escenario.new(escenario_params)
    @escenario.user_id = current_user.id
    if @escenario.save
      create_escenario_optimo
      redirect_to edit_escenario_path(@escenario.id)
    else
      flash[:alert] = @escenario.errors.full_messages
      redirect_to new_escenario_path
    end

  end

  def show
    @edit=false
    respond_to do |f|
      f.html
      f.json
      f.pdf do
        render pdf:'reporte',template:'escenarios/reporte', page_size: 'Letter'
      end
    end
  end

  def edit
    @edit=true
  end

  def update
  end

  def destroy
    if @escenario.update(activo: false)
      flash[:notice] = "Escenario dado de baja con éxito"
      redirect_to root_path
    else
      flash[:alert] = "Ocurrió un problema con la eliminación del escenario"
      redirect_to root_path
    end
  end

  private
  def get_escenarios
    @escenarios = Escenario.where("user_id = ?", current_user.id)
  end

  def get_escenarios_activos
    @escenarios = Escenario.where("activo = ? and user_id = ?", true, current_user.id)
  end

  def find_escenario
    @escenario = Escenario.find(params[:id])
  end

  def get_data_carto
    if @escenario.tipo_escenario === 1
      @datos = CartoMpio.select('id,bloque,nom_mun as municipio, edo as entidad, votantes_pri as "PRI votantes"').where('activo = ?',true)
      @candidatos = HistoricoEscenarioMpio.select('id, escenario_id, candidato_id, carto_mpio_id as "objeto_id",carto_mpio_id, indice').where("escenario_id = ?", params[:id]);
    else
      @datos = CartoDist.select('id, bloque, cve_dist as "no. dist",nom_dist as "Nombre Distrito", votantes_pri as "PRI votantes"')
      @candidatos = HistoricoEscenarioDist.select('id, escenario_id, candidato_id, carto_dist_id as "objeto_id",carto_dist_id, indice').where("escenario_id = ?", params[:id]);
    end
  end

  def new_escenario
    @escenario = Escenario.new
  end

  def escenario_params
    return params.require(:escenario).permit(:nombre,:descripcion,:tipo_escenario)
  end

  def is_active_escenario
    unless @escenario.activo
      flash[:alert] = ["Escenario no se encuentra activo","favor de pedirle al admin que lo active"]
      redirect_to root_path
    end
    unless @escenario.user_id === current_user.id
      flash[:alert] = ["No tienes acceso a ese escenario.","Ese escenario le pertenece a otro usuario."]
      redirect_to root_path
    end
  end

  def escenario_not_found
    flash[:alert] = ["Escenario no encontrado, probablemente no exista"]
    redirect_to root_path
  end

  def create_escenario_optimo
    @escenario.tipo_escenario === 1 ? create_escenario_optimo_mpio(@escenario.id) : create_escenario_optimo_dist(@escenario.id)
  end

  def create_escenario_optimo_mpio escenario_id
    mpios = CartoMpio.where('activo = true').order(votantes_pri: :desc)
    candidatos_asignados = []
    mpios.map do |m|
      candidatos = Candidato.where("carto_mpio_id = ?", m.id).order(encuesta: :desc)
      candidatos.map do |c|
        unless c.id.in? candidatos_asignados
          candidatos_asignados << c.id
          indice = (m.votantes_pri * ( 1 + ((( c.encuesta * 20 ).to_f / 100 ).to_f / 100 ))).round
          HistoricoEscenarioMpio.create(escenario_id: escenario_id, candidato_id: c.id, carto_mpio_id: m.id, indice: indice)
          break
        end
      end
    end
  end

  def create_escenario_optimo_dist escenario_id
    dist = CartoDist.all.order(votantes_pri: :desc)
    candidatos_asignados = []
    dist.map do |d|
      mpios = d.carto_mpios
      condicion = ""
      mpios.each_with_index do |m,i|
        condicion += "carto_mpio_id = #{m.id}"
        condicion += " or " unless i === (mpios.count - 1)
      end
      candidatos = Candidato.where(condicion).order(encuesta: :desc)
      candidatos.map do |c|
        unless c.id.in? candidatos_asignados
          candidatos_asignados << c.id
          indice = (d.votantes_pri * ( 1 + ((( c.encuesta * 20 ).to_f / 100 ).to_f / 100 ))).round
          HistoricoEscenarioDist.create(escenario_id: escenario_id, candidato_id: c.id, carto_dist_id: d.id, indice: indice)
          break
        end
      end
    end
  end
end

app/helpers/escenarios_helper.rb
module EscenariosHelper
  # Constructor del contador de las restricciones de las elecciones
  # tomando en cuenta que en cada bloque debe de existir paridad de género
  # y de manera global 1 de cada 3 debe tener una edad menor a 35 años al día
  # de las elecciones
  def calculate_bloques
    bloques = obtain_n_bloques
    objetos = obtain_n_obj_bloques bloques
    @escenario.tipo_escenario === 2 ? (candidatos_formateados = obtain_candidatos_dist(bloques,objetos)) : (candidatos_formateados = obtain_candidatos_mpio(bloques, objetos))
    return candidatos_formateados
  end

  # Obtener el número de bloques que existe en la base de datos tomando en
  # cuenta el objeto seleccionado, es decir Municipios o Distritos (ambos
  # deben estar descritos como bloques, en caso de no estarlo, se debe de
  # contar como un solo bloque general)
  # Parámetros:
  #   - @datos: Esta variable contiene todos los objetos (mpios o dist) con
  #     su bloque declarado
  #
  # Retorna:
  #   - bloques: este arreglo contiene los bloques que están declarados
  #     en base de datos por parte de los objetos. Ej. [1,2,3]
  def obtain_n_bloques
    bloques = []
    @datos.map do |dato|
      bloques << dato.bloque unless dato.bloque.in? bloques
    end
    return bloques.sort
  end

  def obtain_n_obj_bloques bloques
    objetos = Array.new(bloques.length,0)
    @datos.map do |dato|
      objetos[dato.bloque - 1] += 1
    end
    return objetos
  end

  # Obtiene el número de candidatos separados por bloques y por edad para su
  # posterior formateo a codigo HTML.
  # Parámetros:
  #   - bloques: este arreglo contiene los bloques en los que se
  #     encuentran los objetos en la base de datos.
  #
  # Retorna:
  #   - candidatos_bloques: Este hash contiene el número de
  #   candidatos separados por bloques y a su vez por sexo, para cumplir con
  #   la regla 50/50 en cada bloque, además de contar la edad de cada candidato
  #   para cumplir con la regla 1/3 < 35 años
  #   Ej. {"1":{hombres: 15, mujeres: 16},
  #        "2":{hombres: 4, mujeres: 10}
  #        "1-3":{candidatos: 1, meta: 30}}
  def obtain_candidatos_mpio bloques, objetos
    candidatos_bloques = initialize_hash_bloques bloques, objetos
    @candidatos.map do |candidato|
      candidato.candidato.sexo ? (candidatos_bloques[:"#{candidato.candidato.carto_mpio.bloque}"][:hombres] += 1) : (candidatos_bloques[:"#{candidato.candidato.carto_mpio.bloque}"][:mujeres] += 1)
      edad = obtain_edad_candidato candidato.candidato_id
      candidatos_bloques[:"1-3"][:candidatos] += 1 if edad <= 35
    end
    return candidatos_bloques
  end

  def obtain_candidatos_dist bloques, objetos
    candidatos_bloques = initialize_hash_bloques bloques, objetos
    @candidatos.map do |candidato|
      candidato.candidato.sexo ? (candidatos_bloques[:"#{candidato.carto_dist.bloque}"][:hombres] += 1) : (candidatos_bloques[:"#{candidato.carto_dist.bloque}"][:mujeres] += 1)
      edad = obtain_edad_candidato candidato.candidato_id
      candidatos_bloques[:"1-3"][:candidatos] += 1 if edad <= 35
    end
    return candidatos_bloques
  end

  # Devuelve un hash formateado para su posterior actualización de valores
  # de cada candidato, tomando en cuenta su sexo y su edad. En esta función
  # solo se retorna el "cascarón" del cálculo.
  # Parámetros:
  #   - bloques: Array de los bloques que contiene los bloques en los que se
  #     encuentran los objetos en la base de datos.
  #
  # Retorna:
  #   - hash: Hash formateado para su posterior actualización de valores.
  #   Ej. {"1":{hombres: 0, mujeres: 0},
  #        "2":{hombres: 0, mujeres: 0}
  #        "1-3":{candidatos: 0, meta: 30}}
  def initialize_hash_bloques bloques, objetos
    hash = {}
    # raise @datos.length.inspect
    bloques.map do |bloque|
      temporal_hash = {"#{bloque}": {"mujeres": 0, "hombres": 0, "total": (objetos[bloque - 1])}}
      hash.merge!(temporal_hash)
    end
    return hash.merge!({"1-3": {"candidatos": 0, "meta": (@datos.length / 3 + (@datos.length%3 > 0 ? 1 : 0)).round}})
  end

  # Calcula la edad del candidato hasta el día de la elección
  # Parámetros:
  #   - candidato_id: identificador único del candidato.
  #
  # Retorna:
  #   - edad: años de edad del candidato calculado al día de la elección.
  def obtain_edad_candidato candidato_id
    return Candidato.select("date_part('year',age(date('2017-07-01'),fecha_nacimiento)) as edad").where("id = ?", candidato_id).first.edad
  end

  def formatear_html candidatos_formateados
    text = ''
    valid = false
    candidatos_formateados.map do |cf|
      cf.first.to_s.eql?("1-3") ? valid = rule_13_valid?(cf.last) : valid = block_valid?(cf.last)
      text += "<div class='col s12 m6 l3 padding'><div><div class='title #{valid ? 'correct' : 'wrong'} center'><h5>#{cf.first.to_s}</h5><div class='bloques'><table class='centered'>"
      header = '<tr>'
      column = '<tr>'
      cf.last.map do |c|
        header += "<th>#{c.first.to_s.capitalize}</th>"
        column += "<td id='#{c.first.to_s}_#{cf.first.to_s}'>#{c.last.to_s}</td>"
      end
      header += '</tr>'
      column += '</tr>'
      text += header + column + '</table></div></div></div></div>'
    end
    return text.html_safe
  end

  def block_valid? bloque
    parametro = ((bloque[:total] - 1).to_f / 2).round
    ((bloque[:hombres] >= parametro) && (bloque[:mujeres] >= parametro) && ((bloque[:hombres] + bloque[:mujeres]) === bloque[:total] )) ? (return true) : (return false)
  end

  def rule_13_valid? datos
    datos[:candidatos] >= datos[:meta] ? (return true) : (return false)
  end

  def generate_notas_bloque candidatos_formateados
    mensaje = ''
    candidatos_formateados.map do |cf|
      unless cf.first.to_s.eql?("1-3")
        block_valid?(cf.last) ? (mensaje += "<div class='row correct'><h5 class='w-margin'>Bloque #{cf.first.to_s}:</h5><p class='w-margin'>Se cumple la regla de equidadd de género</p></div>") : (mensaje += get_recomendation_per_block(cf))
      else
        rule_13_valid?(cf.last) ? (mensaje += "<div class='row correct'><h5 class='w-margin'>Regla 1/3</h5><p class='w-margin'>Se cumple la regla 1 de cada 3 deben ser menores a 35 años</p></div>") : (mensaje += get_recomendation_13(cf.last))
      end
    end
    return mensaje
  end
  # 38 Total  20mujeres 3 hombres   38/2=19; 3-20=-17; 19-3=16
  # 37 total  1 mujer   30 hombres  37/2=18; 30-1=29; 18-1=17
  def get_recomendation_per_block bloque
    mensaje = "<div class='row wrong'><h5 class='w-margin'>Bloque #{bloque.first.to_s}:</h5><p class='w-margin'>Falta por asignar "
    cumple_total = (bloque.last[:hombres] + bloque.last[:mujeres] == bloque.last[:total])
    if cumple_total
      valor = bloque.last[:hombres] - bloque.last[:mujeres]
      valor < 0 ? (mensaje += "#{valor.abs/2} #{valor.abs/2 > 1 ? 'hombres' : 'hombre' }.") : (mensaje += "#{valor.abs/2} #{valor.abs/2 > 1 ? 'mujeres' : 'mujer' }.")
    elsif bloque.last[:hombres] > (bloque.last[:total] + bloque.last[:total] % 2) || bloque.last[:mujeres] > (bloque.last[:total] + bloque.last[:total] % 2)
      valor = bloque.last[:hombres] - bloque.last[:mujeres]
      paridad = bloque.last[:total] / 2
      extra = bloque.last[:total] % 2
      valor < 0 ? (mensaje += "#{paridad + extra - bloque[:hombres]} #{paridad + extra - bloque[:hombres] > 1 ? "hombres" : "hombre" }") : (mensaje += "#{paridad + extra - bloque[:mujeres]} #{paridad + extra - bloque[:mujeres] > 1 ? "mujeres" : "mujer" }")
    else
      # raise bloque.inspect
      mensaje += "#{bloque.last[:total] / 2 - bloque.last[:hombres]} #{(bloque.last[:total] / 2 - bloque.last[:hombres]) > 1 ? 'hombres' : 'hombre'} y
      #{bloque.last[:total] / 2 + bloque.last[:total] % 2 - bloque.last[:mujeres]} #{(bloque.last[:total] / 2 + bloque.last[:total] % 2  - bloque.last[:mujeres]) > 1 ? 'mujeres' : 'mujeres'}"
    end
    mensaje += "</div>"
  end

  def get_recomendation_13 bloque
    faltantes = bloque[:meta] - bloque[:candidatos]
    mensaje = "<div class='row wrong'><h5 class='w-margin'>Regla 1/3</h5>"
    mensaje += "<p class='w-margin'>Falta por asignar #{faltantes} #{faltantes > 1 ? "candidatos" : "candidato"}.</p>"
    mensaje += "</div>"
    return mensaje
  end
end

app/views/escenarios/_form.html.erb
<%= form_with model: @escenario, local: true do |f| %>
  <div class="row">
    <div class="col s12">
      <h4>Nombre</h4>
      <div class="input-field">
        <%= f.text_field :nombre, class: 'validate' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col s12">
      <h4>Descripción</h4>
      <div class="input-field">
        <%= f.text_area :descripcion, class: 'materialize-textarea' %>
      </div>
    </div>
  </div>
  <%= f.hidden_field :tipo_escenario, id:'tipo_escenario' %>
  <%= f.button :submit,class:'waves-effect waves-light btn btn-large red' do %>
  Crear<i class="material-icons right">send</i>
  <% end %>
<% end %>

app/views/escenarios/_form_datos.html.erb
<% if @datos.empty? %>
  <p>No hay datos asociados en la base de datos</p>
<% else %>
  <% keys = @datos.first.attributes.keys %>
  <!-- enlace para abrir el modal de restricciones -->
  <a class="waves-effect waves-light btn modal-trigger tooltipped assignment right red" data-position="left" data-delay="50" data-tooltip="Ver resumen de las restricciones" href="#modalRestricciones"></a>
  <table id="datos" class="striped highlight">
    <thead>
      <tr>
        <% keys.map do |k| %>
          <%= "<th>#{k.capitalize}</th>".html_safe unless k === "id" %>
        <% end %>
        <th colspan="2">Candidato</th>
        <th>Votos totales esperados</th>
      </tr>
    </thead>
    <tbody>
      <% @datos.map do |dato| %>
      <tr>
        <% totalv = 0 %>
        <% keys.each do |k| %>
        <%= "<td id=#{k.gsub(" ","_").downcase}_#{dato[:id]}>#{dato[k]}</td>".html_safe unless k === "id" %>
        <% totalv = dato[k] if k === "PRI votantes"%>
        <% end %>
        <td id="candidato_<%= dato['id']%>">
          <%
          candidato = nil
          total_votos = 0
          @candidatos.map do |c|
            if c['objeto_id'] === dato.id
              candidato = Candidato.select("id, nombre, date_part('year',age(date('2017-07-01'),fecha_nacimiento)) as edad, sexo").where("id = ?",c['candidato_id']).first
              total_votos = c['indice']
            end
          end
          %>
          <%= candidato.nil? ? ("<p>No hay candidato asignado aún...</p>".html_safe) : candidato.nombre %>
        </td>
        <td id="candidato_sexo_<%= dato['id']%>" class="hide"><%= candidato.sexo unless candidato.nil? %></td>
        <td id="candidato_edad_<%= dato['id']%>" class="hide"><%= candidato.edad unless candidato.nil? %></td>
        <td>
          <%= "<button data-turbolinks='false' onclick='Electo.Form.showModalCandidato(#{dato["id"]})' class='btn red waves-effect waves-light people tooltipped' data-activar='true' data-position='top' data-delay='50' data-tooltip='Asignar o crear candidato'></button>".html_safe if @edit %>
        </td>
        <td id="total_votos_<%= dato['id']%>"><%= total_votos === 0 ? totalv : total_votos.round%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <!-- Modal para asignar al candidato a la vista y al escenario -->
  <div id="modalCandidato" class="modal">
    <div class="padding-w-top">
      <div class="row w-padding">
        <div class="col s12">
          <ul class="tabs center">
            <li class="tab col s4"><a href="#buscarCandidatoTab">Buscar Candidato</a></li>
            <li class="tab col s4"><a href="#datosCandidatoTab">Datos del candidato</a></li>
          </ul>
        </div>
        <div id="buscarCandidatoTab" class="padding">
          <h5 class="center">Selecciona al candidato</h5>
          <input type="text" id="busquedaCandidato" placeholder="Nombre del candidato" class="flexdatalist" name="busquedaCandidato"
            data-relatives="#relative" data-search-in='["nombre","edad"]' data-visible-properties='["nombre","edad"]'>
          <h5 class="center division">O puedes crear un nuevo candidato...</h5>
          <%= form_with url: candidatos_path(format: :json), method: :post, html: {'onsubmit': 'return Electo.Messages.showMessageCandidatoCreated()'} do |f| %>
          <div class="input-field">
            <p>Nombre del Candidato</p>
            <%= f.text_field "[candidato][nombre]", placeholder: "Nombre del nuevo candidato", required: true %>
          </div>
          <div class="input-field">
            <p>Fecha de nacimiento<p>
            <%= f.date_field "[candidato][fecha_nacimiento]", placeholder:"YYYY-MM-DD", max:"2018-12-10", required: true %>
          </div>
          <div class="input-field">
            <p>Sexo</p>
              <%= f.radio_button "[candidato][sexo]", "true", id: "sexo_masculino", required: true %>
              <%= f.label :sexo_masculino, "Masculino" %>
              <%= f.radio_button "[candidato][sexo]", "false", id:"sexo_femenino" %>
              <%= f.label :sexo_femenino, "Femenino" %>
          </div>
          <div class="input-field">
            <% if @escenario.tipo_escenario == 2 %>
            <p>Municipio</p>
            <%= f.select "[candidato][carto_mpio_id]", options_for_select(CartoMpio.all.map {|m| [m.nom_mun.mb_chars.titleize,m.id]}) %>
            <% else %>
            <%= f.hidden_field "[candidato][carto_mpio_id]", value:'', id: "carto_mpio_id" %>
            <% end %>
          </div>
          <div class="input-field">
            <p>Porcentaje de encuesta</p>
            <%= f.number_field "[candidato][encuesta]", min: 0, max: 100, placeholder: "%", required: true %>
          </div>
          <div class="input-field">
            <input type="submit" value="Crear" class="btn btn-large waves waves-light red" >
          </div>
          <% end %>
        </div>
        <div id="datosCandidatoTab" class="padding">
          <h5>Estos son los datos del candidato</h5>
          <div id="datosCandidatoSeleccionado">
            <p>Actualmente no se ha seleccionado algún candidato.</p>
            <p>Favor de seleccionar un candidato en la pestaña anterior.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- modal inferior para mostrar las restricciones establecidas -->
  <div id="modalRestricciones" class="modal bottom-sheet">
    <div class="modal-content w-padding">
      <div class="title wrong">
        <h4 class="center">Resumen de las Restricciones</h4>
      </div>
      <div class="container">
        <div class="row" id="restriccionesBloques">
          <% bloques = calculate_bloques %>
          <%= formatear_html bloques %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%= link_to 'Generar reporte del escenario actual', escenario_path(params[:id], format: :pdf), class: 'modal-action modal-close waves-effect waves-green btn red', target: "_blank" %>
    </div>
  </div>
<% end %>

app/views/escenarios/edit.html.erb
<h2>Editando la información del escenario '<%= @escenario.nombre %>'</h2>
<%= render 'form_datos' %>
<% content_for :js do %>
$('.tooltipped').tooltip({delay: 50});
$('#modalRestricciones').modal();
$('ul.tabs').tabs();
Electo.Form._tipo_escenario_ = <%= @escenario.tipo_escenario %>
Electo.Form._id_escenario_ = <%= @escenario.id %>
Electo.Table.init(document.getElementById("datos"));
$('#modalCandidato').modal({
  complete: function(){
    $('.flexdatalist').flexdatalist('destroy');
    Electo.Form.clearAllInputs('buscarCandidatoTab','datosCandidatoTab');
  }
});
$('select').material_select();
<% end %>

app/views/escenarios/index.html.erb
<% unless @escenarios.empty? %>
  <div class="row">
  <% @escenarios.map do |e| %>
    <!-- <div class="col s12 m6 l4">
      <div class="card horizontal <%= e.tipo_escenario == 1 ? 'red lighten-5' : 'green lighten-5' %> hoverable">
        <div class="card-image">
          <img src="https://lorempixel.com/100/190/nature/6" alt="<%= e.nombre %>">
        </div>
      </div>
    </div> -->

    <div class="col s12 m6 l4">
      <div class="card <%= e.tipo_escenario == 1 ? 'red lighten-5' : 'green lighten-5' %> hoverable">
        <div class="card-content">
          <span class="card-title"><%= e.nombre %></span>
          <p><%= e.descripcion %></p>
        </div>
        <div class="card-action white-text">
          <%= link_to 'Ver', escenario_path(e), class:"btn blue-grey darken-3" %>
          <%= link_to 'Editar', edit_escenario_path(e), class:"btn blue-grey darken-3" %>
          <button class="btn red darken-3 archive tooltipped right" data-message="true" data-method-http="DELETE" data-position="top" data-delay="50"
            data-tooltip="Archivar escenario" data-delete-url="<%= escenario_path(e.id) %>" data-title-message="¿Quieres eliminar el escenario <%= e.nombre %>?"></button>
        </div>
      </div>
    </div>
  <% end %>
  </div>
<% else %>
  <h4>Ups! parece que no hay escenarios aún</h4>
  <p>Podemos resolverlo creando uno nuevo!</p>
<% end %>
<%= link_to new_escenario_path, class: "btn-floating btn-large waves-effect waves-light red #{'pulse' if @escenarios.empty?} actions-button" do %>
  <i class="material-icons">add</i>
<% end %>
<%= content_for :js do %>
Electo.Messages.init(document.querySelectorAll('[data-message=true]'));
<% end %>

app/views/escenarios/new.html.erb
<div class="full-container">
  <div id="tipo_visualizacion" class="row">
    <h2>Selecciona el tipo de simulación:</h2>
    <div class="col s12 m6">
      <div class="card hoverable">
        <div class="card-image">
          <%= image_tag "3.jpg", alt: "Imagen Municipio" %>
          <!-- <img src="http://materializecss.com/images/sample-1.jpg" alt="Imagen Municipio"> -->
          <a class="btn-floating btn-large halfway-fab waves-effect waves-light-red red add" data-assign="tipo_escenario" data-value="1" data-in="form_escenario" data-out="tipo_visualizacion"></a>
        </div>
        <div class="card-content">
          <span class="card-title">Municipal</span>
          <p>El escenario a mostrar será mediante los datos referentes a los municipios de Michoacán de Ocampo</p>
        </div>
      </div>
    </div>
    <div class="col s12 m6">
      <div class="card hoverable">
        <div class="card-image">
          <%= image_tag "5.jpeg", alt: "Imagen Distrito" %>
          <!-- <img src="http://materializecss.com/images/office.jpg" alt="Imagen Municipio"> -->
          <a class="btn-floating btn-large halfway-fab waves-effect waves-light-red red add" data-assign="tipo_escenario" data-value="2" data-in="form_escenario" data-out="tipo_visualizacion"></a>
        </div>
        <div class="card-content">
          <span class="card-title">Distrital</span>
          <p>El escenario a mostrar será mediante los datos referentes a los distritos de Michoacán de Ocampo</p>
        </div>
      </div>
    </div>
  </div>
  <div id="form_escenario" class="hide padding">
    <a data-in="tipo_visualizacion" data-out="form_escenario" class="btn red right">Volver</a>
    <%= render 'form' %>
  </div>
</div>

<% content_for :js do %>
  Electo.Showable.init(document.querySelectorAll('[data-in]'));
<% end %>

app/views/escenarios/reporte.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <%= wicked_pdf_stylesheet_link_tag 'application' %>
    <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
  </head>
  <body>
    <div class="center gray-pdf">
      <h4>Reporte del escenario <%= @escenario.tipo_escenario.eql?(1) ? 'municipal' : 'distrital' %>: <b><%= @escenario.nombre %></b></h4>
    </div>
    <div class="container">
      <div class="row">
        <div class="col s5">
          <div class="row">
            <h5 class="center gray-pdf">Restricciones por bloque</h5>
            <% bloques = calculate_bloques %>
            <%= formatear_html bloques %>
          </div>
        </div>
        <div class="col s7">
          <div class="row">
            <h5 class="center gray-pdf">Notas sobre las restricciones</h5>
            <div class="col s12">
              <%= generate_notas_bloque(bloques).html_safe %>
            </div>
          </div>
          <div class="row card red lighten-4 padding">
            <h3 class="center"><b>Total de votos esperados:</b></h3>
              <% @escenario.tipo_escenario.eql?(1) ? (votos_totales = HistoricoEscenarioMpio.calculate_votos_totales_escenario(@escenario.id)) : (votos_totales = HistoricoEscenarioDist.calculate_votos_totales_escenario(@escenario.id)) %>
            <h2 class="center"><%= number_with_delimiter(votos_totales[@escenario.id].to_i) %> votos</h2>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/escenarios/show.html.erb
<h2>Visualizando la información del escenario '<%= @escenario.nombre %>'</h2>
<%= render 'form_datos' %>
<% content_for :js do %>
$('.tooltipped').tooltip({delay: 50});
$('#modalRestricciones').modal();
Electo.Table.init(document.getElementById("datos"));
<% end %>